name: GitHub Actions Demo

on:
    push:
        branches: 
            - main
    pull_request: 
        branches: 
            - main

jobs:
    build-job:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello ${{ github.actor }}"
    
    test-job:
        runs-on: ubuntu-latest
        needs: build-job
        steps:
            - run: echo "Repi is ${{ github.repository }}"

    deploy-job:
        runs-on: ubuntu-latest
        needs: test-job
        steps:
            - run: echo "Deploy job ${{ job.status }}"