name: GitHub Actions Demo

on:
    push:
        branches: 
            - main
    pull_request: 
        branches: 
            - main

jobs:
    build-job:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Build job"
    
    test-job:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Test job"
            
    deploy-job:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Deploy job"