name: GitHub Actions Demo

on:
    push:
        branches: 
            - main
    pull_request: 
        branches: 
            - main

jobs:
    build-job:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Bello World Minion"
            - run: echo "Bello World Minion"